version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: dedup_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-dedup_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dedup_password}
      POSTGRES_DB: ${POSTGRES_DB:-deduplication_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dedup_user -d deduplication_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: dedup_api
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-dedup_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dedup_password}
      POSTGRES_DB: ${POSTGRES_DB:-deduplication_db}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data: